// <auto-generated />
namespace FoodOrderMgmtApplication.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class foodorder : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(foodorder));
        
        string IMigrationMetadata.Id
        {
            get { return "202302052036190_food-order"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
